steps:
# Entrypoint [install dependencies]
- name: 'node'
  entrypoint: 'npm'
  args: ['install']

# Docker Build
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/adazolhub-cloud-dev/github.com/adazol123/lab-cloud-run:$COMMIT_SHA', '.']
# Docker Push
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/adazolhub-cloud-dev/github.com/adazol123/lab-cloud-run:$COMMIT_SHA']
options:
  logging: CLOUD_LOGGING_ONLY